<a href="https://colab.research.google.com/github/KimberlySalazarB/C8280/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

NumPy es la librería central para computación científica en Python. Proporciona un objeto de matriz multidimensional de alto rendimiento y herramientas para trabajar con estas matrices.

#### Matrices

Una matriz NumPy es una colección de valores de tipos de datos similares y está indexada por una tupla de números no negativos. El rango de la matriz es el número de dimensiones, y la forma de una matriz es una tupla de números que dan el tamaño de la matriz a lo largo de cada dimensión.


In [4]:
# Ejemplo
from __future__ import division
import time
import numpy as np


tam_vec = 1000
def lista_python():
    t1 = time.time()
    X = range(tam_vec)
    Y = range(tam_vec)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1

def matriz_numpy():
    t1 = time.time()
    X = np.arange(tam_vec)
    Y = np.arange(tam_vec)
    Z = X + Y
    return time.time() - t1

# Completar
t1=lista_python()
t2=matriz_numpy()
print('t1:',t1,'   t2:', t2)

t1: 0.0003323554992675781    t2: 0.0012476444244384766


In [ ]:
#import numpy
#numpy.__version__

Podemos inicializar matrices NumPy a partir de listas de Python anidadas y acceder a los elementos mediante corchetes.

In [8]:
import numpy as np

# Creamos una matriz de rango 1
a = np.array([0, 1, 2])
print (type(a))

# Imprimimos la dimension de la matriz
print (a.shape)
print (a[0])
print (a[1])
print (a[2])

# Cambiamos un elemento de un array
a[0] = 5
print (a)

<class 'numpy.ndarray'>
(3,)
0
1
2
[5 1 2]


In [9]:
# Creamos una matriz de rango 2
b = np.array([[0,1,2],[3,4,5]])
print (b.shape)
print (b)
print (b[0, 0], b[0, 1], b[1, 0])

(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


In [10]:
print ( b.shape)
print ( b[0, 0], b[0, 1], b[1, 0])

(2, 3)
0 1 3


### Creación de una matriz NumPy

NumPy también proporciona muchas funciones integradas para crear matrices. La mejor manera de aprender esto es a través de ejemplos, así que pasemos al código.

In [11]:
# Creamos una matriz 3x3 de todos ceros
a = np.zeros((3,3))
print (a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
# Creamos una matriz 2x2 de todos 1
b = np.ones((2,2))
print (b)

[[1. 1.]
 [1. 1.]]


In [13]:
# Creamos una matriz 3x3 constantes
c = np.full((3,3), 7)
print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [14]:
# Creamos una matriz 3x3 con valores aleatorios
d = np.random.random((3,3))
print (d)

[[0.36127639 0.03045329 0.44564052]
 [0.14922039 0.34046983 0.09811612]
 [0.38240367 0.97031769 0.87156024]]


In [15]:
# Creamos una matriz identidad 3x3
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# Convertir una lista en una matriz
f = np.array([2, 3, 1,0])
print(f)

[2 3 1 0]


In [20]:
# arange() crea matrices con valores que se incrementan regularmente
# Completar
np.arange(start=0,stop=20,step=2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
np.arange(start=4,stop=70,step=10)

array([ 4, 14, 24, 34, 44, 54, 64])

In [26]:
# Mezcla de tupla y listas
# Completar
mezcla=[(1,2,3),'q','e','t',7]
mezcla

[(1, 2, 3), 'q', 'e', 't', 7]

In [ ]:
# Crear una matriz de rango con tipo de datos flotante
i = np.arange(1, 8, dtype=np.float64)
print(i)

`linspace()`  crea matrices con un numero especifico de elementos que están espaciados por igual entre los valores inicial y final especificados

In [6]:
# Completa
np.linspace(start=0,stop=2,num=20)

array([0.        , 0.10526316, 0.21052632, 0.31578947, 0.42105263,
       0.52631579, 0.63157895, 0.73684211, 0.84210526, 0.94736842,
       1.05263158, 1.15789474, 1.26315789, 1.36842105, 1.47368421,
       1.57894737, 1.68421053, 1.78947368, 1.89473684, 2.        ])

In [7]:
np.linspace(start=4,stop=7,num=20)

array([4.        , 4.15789474, 4.31578947, 4.47368421, 4.63157895,
       4.78947368, 4.94736842, 5.10526316, 5.26315789, 5.42105263,
       5.57894737, 5.73684211, 5.89473684, 6.05263158, 6.21052632,
       6.36842105, 6.52631579, 6.68421053, 6.84210526, 7.        ])

### Tipos de datos
Una matriz es una colección de elementos del mismo tipo de datos y NumPy admite y proporciona funciones integradas para construir matrices con argumentos opcionales para especificar explícitamente los tipos de datos requeridos.

In [ ]:
# Numpy escoge el tipo de datos
x = np.array([0, 1])
y = np.array([2.0, 3.0])

# Fuerza un tipo de datos en particular
z = np.array([5, 6], dtype=np.int64)
print (x.dtype, y.dtype, z.dtype)

**Ejercicio** Completa el siguiente  código.

In [31]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)  # matriz 1-d
x2 = np.random.randint(10, size=(5, 4))  # matriz-2d
x3 = np.random.randint(10, size=(2, 4, 5)) # matriz-3d

# Imprime los atributos : dim, shape, size, dtype, itemsize y nbytes

# Completar
print('atributosx1: ', 'ndim:', x1.ndim, ' shape:',x1.shape, ' size:',x1.dtype, ' itemsize:',x1.itemsize, ' nbytes:',x1.nbytes)
print('atributosx2: ', 'ndim:', x2.ndim, ' shape:',x2.shape, ' size:',x2.dtype, ' itemsize:',x2.itemsize, ' nbytes:',x2.nbytes)
print('atributosx3: ', 'ndim:', x3.ndim, ' shape:',x3.shape, ' size:',x3.dtype, ' itemsize:',x3.itemsize, ' nbytes:',x3.nbytes)

atributosx1:  ndim: 1  shape: (6,)  size: int64  itemsize: 8  nbytes: 48
atributosx2:  ndim: 2  shape: (5, 4)  size: int64  itemsize: 8  nbytes: 160
atributosx3:  ndim: 3  shape: (2, 4, 5)  size: int64  itemsize: 8  nbytes: 320


### Indexación de matrices

NumPy ofrece varias formas de indexar en matrices. La sintaxis estándar de Python `x[obj]` se puede usar para indexar la matriz NumPy, donde `x` es la matriz y `obj` es la selección.

Hay tres tipos de indexación disponibles:

* Acceso al campo

* Recorte básico

* Indexación avanzada

#### Acceso al campo

Si el objeto ndarray es una matriz estructurada, se puede acceder a los campos de la matriz indexando la matriz con cadenas, como un diccionario. La indexación de `x['field-name']` devuelve una nueva vista de la matriz, que tiene la misma dimensión que `x`, excepto cuando el campo es una submatriz  que contiene sólo la parte de los datos en el campo especificado. Los tipos de datos se obtienen con `x.dtype['field-name']`.

In [32]:
x = np.zeros((3,3), dtype=[('a', np.int32), ('b', np.float64, (3,3))])
print(x)

[[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]
 [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]
 [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]]


In [33]:
print ("x['a'].shape: ",x['a'].shape)
print ("x['a'].dtype: ", x['a'].dtype)

print ("x['b'].shape: ", x['b'].shape)
print ("x['b'].dtype: ", x['b'].dtype)

x['a'].shape:  (3, 3)
x['a'].dtype:  int32
x['b'].shape:  (3, 3, 3, 3)
x['b'].dtype:  float64


#### Recorte básico

Las matrices NumPy se pueden dividir, de forma similar a las listas. Debe especificar un segmento para cada dimensión de la matriz, ya que las matrices pueden ser multidimensionales.

La sintaxis de división básica es `i: j: k`, donde `i` es el índice inicial, `j` es el índice final, `k` es el paso y `k` no es igual a 0. Esto selecciona los elementos `m` en la dimensión correspondiente, con valores de índice `, i + k, ...,i + (m - 1)k` donde `m = q + (r distinto de 0)`,  `q` y `r` son el cociente y el resto se obtiene dividiendo `j - i` entre `k`: `j - i = qk + r`, de modo que `i + (m - 1) k < j`.

In [34]:
x = np.array([5, 6, 7, 8, 9])
x[1:7:2]

array([6, 8])

La `k` negativa hace que los pasos vayan hacia índices más pequeños. Los `i` y `j` negativos se interpretan como `n + i` y `n + j` donde `n` es el número de elementos en la dimensión correspondiente.

In [35]:
print (x[-2:5])
print (x[-1:1:-1])

[8 9]
[9 8 7]


Si `n` es el número de elementos en la dimensión que se está recortando. Entonces, si no se proporciona `i`, el valor predeterminado es `0` para  `k > 0` y `n-1` para `k < 0`. Si no se proporciona `j`, el valor predeterminado es `n` para `k > 0` y `-1` para `k < 0`. Si no se proporciona `k`, el valor predeterminado es `1`. Ten en cuenta que `::` es lo mismo que `:` y significa seleccionar todos los índices a lo largo de este eje.

In [36]:
x[4:]

array([9])

Si el número de objetos en la tupla de selección es menor que N , entonces se asume `:` para cualquier dimensión subsiguiente.

In [42]:
# Completar
x[:-1]

array([5, 6, 7, 8])

Los puntos suspensivos se expanden al número de : objetos necesarios para hacer una tupla de selección de la misma longitud que `x.ndim`. Solo puede haber una sola elipsis presente.

In [43]:
print(x)

[5 6 7 8 9]


In [44]:
x[...,0]

array(5)

#### Ejercicio

1. Crea una matriz de rango `2` con dimension `(3, 4)`

2. Usa el recorte para extraer la submatriz que consta de las primeras `2` filas y las columnas `1` y `2`.

3. Una parte de una matriz es solo una vista de los mismos datos, comprueba quecualquier modificación modificará la matriz original.



In [60]:
# Tu respuesta
a = np.array([[3,5,6,8], [7,6,3,5], [6,13,11,12]])
recorte=a[:2, 0:2]
print("matriz:",a, a.shape)
print("recorte:",recorte)

matriz: [[ 3  5  6  8]
 [ 7  6  3  5]
 [ 6 13 11 12]] (3, 4)
recorte: [[3 5]
 [7 6]]


Se puede acceder a la matriz de la fila central de dos maneras.

* Las partes junto con la indexación de enteros darán como resultado una matriz de rango inferior.

* El uso de solo recortes dará como resultado el mismo rango matriz.

In [57]:
# Creamos una matriz de rango 2 array con dimensión (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Dos formas de acceder a los datos en la fila central de la matriz. La combinación de la indexación de enteros con recortes produce una matriz de menor rango, mientras que el uso de solo recortes produce una matriz del mismo rango que la matriz original:

In [58]:
fila_r1 = a[1, :]    # Vista de rango 1 de la segunda fila de a
fila_r2 = a[1:2, :]  # Vista de rango 2 de la segunda fila de a
fila_r3 = a[[1], :]  # Vista de ranfo 2 de la segunda fila de a
print (fila_r1, fila_r1.shape)
print (fila_r2, fila_r2.shape)
print (fila_r3, fila_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


Podemos hacer la misma distinción al acceder a las columnas de una matriz.

In [61]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print (col_r1, col_r1.shape)
print (col_r2, col_r2.shape)

[ 5  6 13] (3,)
[[ 5]
 [ 6]
 [13]] (3, 1)


### Indexación avanzada


In [123]:
a = np.array([[1,2], [3, 4]])
print (a[[0, 1], [0, 1]])

# El ejemplo de indexacion de una matriz entera es equivalente a esto:
# completar
print(np.array([a[0, 0],a[1,1]]))


[1 4]
[1 4]


Al usar la indexacion de un matriz de enteros, puede reutilizar el mismo elemento de la matriz de origen:

In [125]:
print (a[[0, 0], [1, 1]])

# Equivalente al ejemplo de indexacion de matriz de enteros
# completar
print(np.array([a[0, 1],a[0,1]]))


[2 2]
[2 2]


Un asunto  importante y extremadamente útil acerca de los recortes de una  matriz es que devuelven  *vistas (`views`)* en lugar de *copias (`copies`)*  de los datos de la matriz. Este es un área en la que NumPy  difiere de la lista de Python:  en las listas, estas son copias.

In [73]:
np.random.seed(0)
x2 = np.random.randint(10, size=(5, 4))
x2

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6],
       [8, 8, 1, 6],
       [7, 7, 8, 1]])

In [74]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[5 0]
 [7 9]]


In [75]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  0]
 [ 7  9]]


Este comportamiento predeterminado es realmente muy útil: significa que cuando trabajamos con grandes conjuntos de datos, podemos acceder y procesar partes de estos conjuntos de datos sin necesidad de copiar el búfer de datos.

A pesar de las características  de las `vistas` de una  matriz, a veces es útil copiar de forma explícita los datos dentro de una matriz o una submatriz. Esto se puede hacer  con el método `copy()`:

In [76]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  0]
 [ 7  9]]


In [77]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  0]
 [ 7  9]]


In [78]:
print(x2)

[[99  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]
 [ 8  8  1  6]
 [ 7  7  8  1]]


### Reshaping

In [108]:
x4 = np.arange(1, 10).reshape((3, 3))
print(x4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Ten en cuenta que para que esto funcione, el tamaño de la matriz inicial debe coincidir con el tamaño de la matriz rediseñada. Siempre que sea posible, el método `reshape` utilizará una `vista` sin copia de la matriz inicial.

Otro patrón de `reshaping `, es la conversión de una matriz unidimensional en una fila o columna de una matriz bidimensional. Esto se puede hacer con el método `reshape`  o más fácilmente haciendo uso de `newaxis` dentro de una operación de división:

In [109]:
x5 = np.array([1, 2, 3])
x5

array([1, 2, 3])

In [128]:
# vector fila via reshape
# completar
x5.reshape(3)

array([1, 2, 3])

In [133]:
# vector fila con newaxis
# completar
fila=x5[np.newaxis, :]
fila

array([[1, 2, 3]])

In [135]:
# vector columna via reshape
# completar
x5.reshape(-1, 1)

array([[1],
       [2],
       [3]])

In [134]:
# vector columna con newaxis
# completar
columna=x5[:,np.newaxis]
columna

array([[1],
       [2],
       [3]])

### Concatenación y  separación


In [136]:
x = np.array([4, 5, 6])
y = np.array([7, 8, 9])
np.concatenate([x, y])

array([4, 5, 6, 7, 8, 9])

In [137]:
# concatenacion de dos o mas matrices
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 4  5  6  7  8  9 99 99 99]


In [138]:
# concatendo una matriz dos veces
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

Para trabajar con matrices de distintas dimensiones, se usan las funciones `vstack` y `hstack`:

In [141]:
x = np.array([0, 1, 2])
grid = np.array([[3, 4, 5],
                 [6, 5, 4]])

# Se junta la matriz de manera vertical
# Completar
np.vstack((x, grid))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 5, 4]])

In [144]:
# Se junta la matriz de manera horizontal
y = np.array([[23],
              [23]])
# Completar
np.hstack((y,grid))

array([[23,  3,  4,  5],
       [23,  6,  5,  4]])

Lo contrario de la concatenación es la división o separación, que es implementado por las funciones `np.split`, `np.hsplit` y `np.vsplit`. Para cada uno de estas funciones , podemos pasar una lista de índices que dan los puntos de división.

Ver:[https://numpy.org/doc/stable/reference/generated/numpy.split.html](https://numpy.org/doc/stable/reference/generated/numpy.split.html)

In [145]:
x = [1, 2, 3, 44, 95, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [44 95] [3 2 1]


In [146]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [147]:
grid1, grid2 = np.vsplit(grid, [2])
print(grid1)
print(grid2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [148]:
grid3, grid4 = np.hsplit(grid,[2])
print(grid3)
print(grid4)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### Fancy


In [149]:
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [150]:
# Accedemos a tres elementos diferentes
[x[1], x[5], x[2]]

[92, 20, 14]

Alternativamente, podemos pasar una sola lista o matriz de índices para obtener el mismo resultado:

In [156]:
# Completar
matriz = x[[1,5,2]]
matriz

array([92, 20, 14])

Cuando se utiliza fancy, la forma del resultado refleja la forma de las matrices de índice en lugar de la forma de la matriz que se indexa y trabaja  en múltiples  dimensiones:

In [159]:
# Completar
fancy = x[[1, 5, 2]]
fancy

array([92, 20, 14])

In [157]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Al igual que con la indexación estándar, el primer índice se refiere a la fila, y el segundo a la columna:

In [160]:
fila = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[fila, col]

array([ 2,  5, 11])

Observa que el primer valor en el resultado es `X[0, 2]`, el segundo es `X[1, 1]`  y el tercero es `X[2, 3]`. El emparejamiento de índices en la indexación fancy  sigue todas las reglas del broadcasting, por ejemplo, si combinamos un vector de columna y un vector de fila dentro de los índices, obtenemos un resultado bidimensional:

In [185]:
# Completar
# use fancy indexing to select specific rows
[X[0][2], X[1][1], X[2][3]]



[2, 5, 11]

Aquí, cada valor de fila se empareja con cada vector de columna, exactamente como se hace en broadcasting  de operaciones aritméticas. Por ejemplo:

In [189]:
# Completar
rels= X + 10
rels

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

Siempre es importante recordar que en  la indexación fancy, el valor de retorno refleja la forma del broadcasting  de los índices, en lugar de la forma de la matriz que se indexa.

Para operaciones  más potentes, la indexación adornada se puede combinar con los otros esquemas de indexación que existen:

In [232]:
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [235]:
# Combinando el indexado fancy y indices simples
# Completar
r= X[[0, 1, 2], [1, 2, 3]]
r

array([ 1,  6, 11])

In [236]:
# Combinando el indexado fancy y el recorte
# Completar
filas = [0, 2]
columnas = [1, 3]

r = X[filas, :][:, columnas]
r

array([[ 1,  3],
       [ 9, 11]])

Así como el fancy  se puede utilizar para acceder a partes de una matriz, también se puede utilizar para modificar partes de una matriz. Por ejemplo, si  tenemos una matriz de índices y nos gustaría establecer los elementos correspondientes en una matriz a algún valor, podemos hacer lo siguiente:

In [237]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


Los índices repetidos con estas operaciones pueden causar algunos resultados potencialmente inesperados. Considera lo siguiente:

In [251]:
x = np.zeros(10)
x[[0, 0]] = [4, 6]
print(x)

[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


El resultado de esta operación es asignar primero  `x[0] = 4`, seguido por `x[0] = 6`. Pero el resultado es que `x[0]` contiene el valor 6.

Considera la siguiente operación:

In [252]:
i = [2, 3, 3, 4, 4, 4]
x[i] += 1
print(x)

[6. 0. 1. 1. 1. 0. 0. 0. 0. 0.]


En este caso algún resultado inesperado se debe conceptualmente  a que `x[i] +=1` se entiende como una abreviatura de `x[i] = x [i] + 1`. Cuando `x[i] + 1` es evaluado el resultado es asignado  a los índices en `x` . Con esto en mente, no es que el aumento que ocurre varias veces, sino la asignación, que conduce a los resultados  no intuitivos.

Si quieremos  el otro comportamiento donde se repite la operación, se puede utilizar el método `at()` de `ufuncs`:

In [253]:
# Completar
np.add.at(x, i, 1)
print(x)

[6. 0. 2. 3. 4. 0. 0. 0. 0. 0.]


El método `at()` realiza una aplicación  del operador dado en los índices especificados (aquí, `i`) con el valor especificado (aquí, `1`).

###  Expresiones vectorizadas

### Agregaciones


In [211]:
L = np.random.random(100)
sum(L)

46.22296570937432

La sintaxis es bastante similar a la función de `sum` de  `NumPy`  y el resultado es el mismo en el caso más simple:

In [212]:
np.sum(L)

46.22296570937433

Sin embargo, debido a que la operación se ejecuta  en código compilado, la versión `NumPy` de la operación se calcula mucho más rápidamente:

In [213]:
matriz_grande = np.random.rand(1000000)
%timeit sum(matriz_grande)
%timeit np.sum(matriz_grande)

108 ms ± 29.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
434 µs ± 113 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


La función `sum` y la función `np.sum` no son idénticas, lo que a veces puede conducir a la confusión.  En particular, sus argumentos opcionales tienen significados diferentes  y `np.sum` es válido a  varias dimensiones de una matriz.

In [214]:
# Otras funciones min y max
min(matriz_grande), max(matriz_grande)

(1.3299024816948446e-06, 0.9999967084337831)

In [215]:
%timeit min(matriz_grande)
%timeit np.min(matriz_grande)

83.4 ms ± 26 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
443 µs ± 11.3 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Todas estas funciones también están disponibles como métodos en la clase `ndarray`. Por ejemplo, `np.mean(data)` y `data.mean()` en el ejemplo siguiente son equivalentes:

In [216]:
data = np.random.normal(size=(15, 15))
np.mean(data)

-0.1594453598484134

In [217]:
data.mean()

-0.1594453598484134

Un tipo común de operación de agregación es un agregado a lo largo de una fila o columna.

In [218]:
M = np.random.random((5, 6))
print(M)

[[0.19248812 0.33241001 0.04126978 0.12285432 0.60913146 0.45697108]
 [0.97325607 0.46621981 0.55416456 0.63075697 0.75503225 0.42151414]
 [0.43553927 0.57139311 0.12773254 0.63080587 0.00288583 0.53456719]
 [0.70458505 0.42018037 0.27033666 0.91852781 0.08612059 0.32703493]
 [0.59619505 0.86158439 0.33884043 0.48929733 0.25763178 0.21687485]]


De forma predeterminada, cada función de agregación de  `NumPy`  devolverá el agregado sobre toda la matriz:

In [219]:
M.sum()

13.346201618662969

Las funciones de agregación toman un argumento adicional que especifica el eje a lo largo del cual se calcula el agregado. Por ejemplo, podemos encontrar el valor de la suma y el  mínimo de cada columna especificando `axis = 0`:

In [220]:
M.sum(axis= 0)

array([2.90206356, 2.65178769, 1.33234397, 2.7922423 , 1.71080192,
       1.95696219])

In [221]:
data = np.random.normal(size=(5, 10, 15))
data.sum(axis=0).shape

(10, 15)

In [222]:
data.sum(axis=(0, 2)).shape

(10,)

In [223]:
data.sum()

-24.220796002992333

Algunas funciones de agregación en `Numpy ` son :


|Nombre de funcion  | VersionNaN-safe     | Descripcion                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Calcula suma de elementos                     |
| ``np.prod``       | ``np.nanprod``      | Calcula el producto de elementos              |
| ``np.mean``       | ``np.nanmean``      | Calcula la media de elementos                 |
| ``np.std``        | ``np.nanstd``       | Calcula la desviacion estandar                |
| ``np.var``        | ``np.nanvar``       | Calcula la  varianza                          |
| ``np.min``        | ``np.nanmin``       | Encuentra el minimo valor                     |
| ``np.max``        | ``np.nanmax``       | Encuentra el maximo valor                     |
| ``np.argmin``     | ``np.nanargmin``    | Encuenta el index del minimo valor            |
| ``np.argmax``     | ``np.nanargmax``    | Encuentra el index del maximo valor           |
| ``np.median``     | ``np.nanmedian``    | Calcula la mediana de elementos               |
| ``np.percentile`` | ``np.nanpercentile``| Calcula el rango estatistico de elementos     |
| ``np.any``        | N/A                 | Evalua si algun elemento es true              |
| ``np.all``        | N/A                 | Evalua si todos los elementos son true        |



#### Broadcasting


In [224]:
a = np.array([0, 1, 2])
b = np.array([2, 6, 1])
a + b

array([2, 7, 3])

El  `broadcasting` permite que estos tipos de operaciones binarias se realicen en matrices de diferentes tamaños; por ejemplo, podemos añadir  un escalar (una matriz de dimensión cero) a una matriz:

In [225]:
a + 5


array([5, 6, 7])

Podemos extender de manera similar esto a matrices de mayor dimensión. Veamos el resultado cuando agregamos una matriz unidimensional a una matriz bidimensional:

In [226]:
A = np.arange(16).reshape(4, 4)
b = np.arange(4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [227]:
A + b

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

Podemos aplicar el  `broadcasting` en dos matrices. Considere el siguiente ejemplo:

In [262]:
# Completar
m1 = np.array([[4,5, 6],[7, 8,9]])
m1

array([[4, 5, 6],
       [7, 8, 9]])

In [263]:
# Completar
m2 = np.array([[10],[20]])
m2

array([[10],
       [20]])

In [264]:
# Completar
m1+m2

array([[14, 15, 16],
       [27, 28, 29]])

###  Regla del broadcasting

El `broadcasting` en `NumPy` sigue un estricto conjunto de reglas para determinar la interacción entre dos matrices :

* Regla 1: Si las dos matrices difieren en su número de dimensiones, la forma de la matriz que tiene menos dimensiones se rellena con unos en el lado principal (izquierdo).

* Regla 2: Si la forma de los dos matrices no coincide con ninguna dimensión, la matriz con la forma igual a 1 en esa dimensión se estira para que coincida con la otra dimensión.

* Regla 3: Si en cualquier dimensión los tamaños son distintos y ninguno es igual a 1, se genera un error.

### Un útil truco:

In [238]:
J = np.arange(0, 40, 10)
J.shape

(4,)

In [239]:
J = J[:, np.newaxis]  # agregamos un nuevo eje ->  matriz 2D
J.shape

(4, 1)

In [240]:
J

array([[ 0],
       [10],
       [20],
       [30]])

In [241]:
J + 3

array([[ 3],
       [13],
       [23],
       [33]])

### Comparaciones, máscaras y lógica Booleana


In [242]:
a1 = np.array([1, 2, 3, 4])
b1 = np.array([4, 3, 2, 1])
a1 < b1

array([ True,  True, False, False])

In [243]:
np.all(a1 < b1)

False

In [254]:
np.any(a1 < b1)

True

In [255]:
if np.all(a1 < b1):
    print(" Todos los elementos en a1 son menores que los elementos en b1 ")
elif np.any(a1 < b1):
    print("Algunos elementos en a1 son menores que los elementos de b1")
else:
    print("Todos los elementos en b1 son menores que los elementos de a1")

Algunos elementos en a1 son menores que los elementos de b1


Al aparecer en una expresión aritmética junto con un número escalar, u otra matriz `NumPy` con un tipo de datos numéricos, una matriz booleana se convierte en una matriz numérica con valores `0` y `1` en lugar de `False` y `True`, respectivamente.

In [269]:
# Completar
matriz = np.array([[True, False], [False, True]])

numero = 20

In [270]:
re = matriz + numero
print(re)

[[21 20]
 [20 21]]


Esta es una propiedad útil para la computación condicional, como cuando se definen funciones.

In [265]:
def pulso(t, posicion, altura, ancho):
    return altura * (t >= posicion) * (t <= (posicion + ancho))
# Completar

### Matrices booleanas como máscaras

Revisar: [masked array](https://docs.scipy.org/doc/numpy/reference/maskedarray.html).

In [271]:
k = np.array([1, 3, -1, 5, 7, -1])
mask = (k < 0)
mask

array([False, False,  True, False, False,  True])

In [272]:
# Un ejemplo bidimensional
rng = np.random.RandomState(0)
z1 = rng.randint(10, size=(3, 4))
z1

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [276]:
# Completar
mask = (z1 < 3)
mask

array([[False,  True, False, False],
       [False, False, False, False],
       [ True, False, False, False]])

Ahora, para seleccionar estos valores de la matriz, podemos simplemente indexar en esta matriz booleana, esto se conoce como una operación de `enmascaramiento`:

In [278]:
# Completar
enmascaramiento= z1[mask]
enmascaramiento

array([0, 2])

El siguiente ejemplo muestra cómo sumar la matriz de enmascaramiento,  donde `True` representa uno y `False` representa 0.

In [279]:
# Completar
suma_enmascaramiento = np.sum(mask)
suma_enmascaramiento

2

### Lectura recomendada: [Numpy Reference](https://docs.scipy.org/doc/numpy/reference/).